[project]
title = "Hospital Data Analysis"
version = "1.0"
port = 8501
slug = "hospital-analysis"
entrypoint = "hello.py"

][build]
exclude = ["dataset/", "data/HospInfo.csv", "data/HospInfo.zip", "venv/"]
