[project]
title = "Hospital Data Analysis Dashboard"
version = "1.0"
port = 8501
slug = "hospital-analysis"
entrypoint = "hello.py"

[build]
exclude = ["data/", "venv/", "__pycache__/", ".git/", "*.log"]

